# Generated by Django 4.0.6 on 2023-01-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_user_ia_agent_user_is_organisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ia_agent',
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
